---
- name: run nexus
  docker_container:
    name: nexus
    image: sonatype/nexus3:3.14.0
    state: started
    restart_policy: unless-stopped
    network_mode: host
  # work around for https://github.com/ansible/ansible/issues/20604
  become: true
