---
# mount -o rw,guest,gid=1000,uid=1000,iocharset=utf8,file_mode=0664,dir_mode=0775 -t cifs //{ip}/Share /{directory}
- block:

  - name: install samba
    apt: name=samba state=latest

  - name: start samba
    service: name=smbd state=started enabled=yes

  - name: create global conf
    template:
      src: smbd-global.conf.j2
      dest: /etc/samba/smbd-global.conf
      owner: root
      group: root
      mode: 0644

  - name: configure samba
    lineinfile:
      dest: /etc/samba/smb.conf
      line: "include = /etc/samba/smbd-global.conf"
    notify: samba restart

  - include_tasks: _create-share.yml
    vars:
      samba_share: "{{ item }}"
      samba_conf_file: "/etc/samba/my-smbd-{{ item.name }}.conf"
    with_items: "{{ samba.shares }}"

  become: true
