---
- block:

  - name: install samba
    apt: name=samba state=latest

  - name: start samba
    service: name=smbd state=started enabled=yes

  - name: create samba custom configuration
    template:
      src: my_smbd.conf.j2
      dest: /etc/samba/my_smbd.conf
      owner: root
      group: root
      mode: 0644

  - name: create share directory
    file:
      path: "{{ samba.share_dir }}"
      state: directory
      owner: "{{ samba.user }}"
      group: "{{ samba.group }}"
      mode: 0775

  - name: configure samba
    lineinfile:
      dest: /etc/samba/smb.conf
      line: "include = /etc/samba/my_smbd.conf"
    notify: samba restart

  become: true